runtime: go114
instance_class: F1
automatic_scaling:
  max_idle_instances: 1
  min_pending_latency: automatic  # default value
  max_pending_latency: 30ms
  max_concurrent_requests: 100

default_expiration: "7d"

env_variables:
  HOST: "https://www.slothninja.com"
  DS_PROJECT_ID: "go-slothninja-games"
  DS_HOST: "www.slothninja.com"
  USER_PROJECT_ID: "user-slothninja-games"
  DS_USER_HOST: "user.slothninja.com"
  CLIENT_ID: "672111572490-cq4vgrlatrtds46ajako0qrijbf1nkq8n.apps.gooleusercontent.com" 
  CLIENT_SECRET: "QrSbRG4f876G79WPvm95mr5f"
  NODE_ENV: "production"
  MJ_API_KEY_PUB: "0b66e3cf5d4b5a5c536ef1a289b58d79"
  MJ_API_KEY_PRIV: "e4ba83076c32f4732e84a1b05cb4e3e5"
  COOKIE_URL: "https://user.slothninja.com/cookie"
  LOGIN_HOST: "https://user.slothninja.com"

inbound_services:
- warmup

handlers:
- url: /stylesheets
  static_dir: public/stylesheets

- url: /scripts
  static_dir: public/scripts
  
- url: /javascripts
  static_dir: public/javascripts

- url: /js
  static_dir: public/js

- url: /images
  static_dir: public/images
  
- url: /images/*
  static_dir: public/images
  
- url: /rules
  static_dir: public/rules

- url: /favicon\.ico
  static_files: public/images/favicon.ico
  upload: public/images/favicon\.ico

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots\.txt

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
